class_name AlphabetSoundResource extends Resource

@export var a: AudioStream
@export var b: AudioStream
@export var c: AudioStream
@export var d: AudioStream
@export var e: AudioStream
@export var f: AudioStream
@export var g: AudioStream
@export var h: AudioStream
@export var i: AudioStream
@export var j: AudioStream
@export var k: AudioStream
@export var l: AudioStream
@export var m: AudioStream
@export var n: AudioStream
@export var o: AudioStream
@export var p: AudioStream
@export var q: AudioStream
@export var r: AudioStream
@export var s: AudioStream
@export var t: AudioStream
@export var u: AudioStream
@export var v: AudioStream
@export var w: AudioStream
@export var x: AudioStream
@export var y: AudioStream
@export var z: AudioStream
